# def count_vowels(x):
#     vowels="aeiouAEIOU"
#     if len(x)==0:
#         return "invalid input"
#     else:
#         a=[]
#         for i in range(0,len(x)):
#             if x[i] not in " ":
#                 a.append(x[i])
#         return a
       
       
# print(count_vowels("I like code everyday"))



#print count which word has more "a"
#input=["apple","appeal","after","banish"]
#output="appeal" a->2